# Generated by Django 4.2.19 on 2025-11-28 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='passwordresettoken',
            name='is_used',
            field=models.BooleanField(default=False),
        ),
    ]
